name: Bug Report
description: Create a report to help us improve ELRS Mobile
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: phone-model
    attributes:
      label: Phone Model
      description: e.g., Pixel 7, Samsung S23, etc.
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android Version
      description: e.g., Android 13, Android 14
    validations:
      required: true
  - type: input
    id: elrs-target
    attributes:
      label: ELRS Target
      description: The name of the receiver or transmitter you are flashing (e.g., BetaFPV Nano RX)
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Sentry Event ID or Logs
      description: If you submitted a debug report in the app, please provide the Event ID shown in the snackbar.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
